version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"

  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data 

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      - database
      - redis
    env_file:
      - .env/development/database
      - .env/development/web

volumes:
  db_data:
  gem_cache:
  redis: